# Generated by Django 5.2.16 on 2026-07-16 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("short_description", models.TextField()),
                ("target_customer", models.CharField(blank=True, max_length=255)),
                ("problems_solved", models.TextField(blank=True)),
                ("benefits", models.TextField(blank=True)),
                ("pricing_model", models.CharField(blank=True, max_length=120)),
                (
                    "starting_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("website", models.URLField(blank=True)),
                ("booking_link", models.URLField(blank=True)),
                ("status", models.CharField(default="active", max_length=32)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "name"),
                        name="unique_product_per_workspace",
                    )
                ],
            },
        ),
    ]
