# Generated by Django 5.2.16 on 2026-07-16 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                ("provider", models.CharField(default="mock", max_length=32)),
                ("bot_username", models.CharField(blank=True, max_length=180)),
                ("bot_id", models.CharField(blank=True, max_length=80)),
                ("webhook_url", models.URLField(blank=True)),
                (
                    "webhook_status",
                    models.CharField(default="mock_active", max_length=32),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.TextField(blank=True)),
                ("encrypted_bot_token", models.TextField(blank=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TelegramChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("chat_type", models.CharField(default="group", max_length=32)),
                ("telegram_chat_id", models.CharField(max_length=80)),
                ("monitoring_enabled", models.BooleanField(default=True)),
                ("admin_approved", models.BooleanField(default=True)),
                ("reply_mode", models.CharField(default="approval", max_length=32)),
                ("minimum_score", models.PositiveIntegerField(default=50)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="telegram_integration.telegramconnection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "telegram_chat_id"),
                        name="unique_chat_per_workspace",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telegram_user_id", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=180)),
                ("username", models.CharField(blank=True, max_length=180)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "telegram_user_id"),
                        name="unique_contact_per_workspace",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("update_id", models.CharField(max_length=120)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(default="processed", max_length=32)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_integration.telegramconnection",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "update_id"),
                        name="unique_update_per_connection",
                    )
                ],
            },
        ),
    ]
